# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Tyler Thrailkill"
repository:         snowe2010/snowe2010.github.io

author:
  # facebook:         your-id
  # youtubeUser:      your-id
  # youtubeChannel:   your-id
  # twitter:          your-id
  github:           snowe2010
  stackoverflow:    1394698
  # quora:            your-id
  linkedin:         tylerthrailkill
  # pinterest:        your-id
  # googlePlus:       your-id
  # instagram:        your-id
  # reddit:           your-id
  # medium:           your-id
  # tumblr:           your-id
  email:            tyler.b.thrailkill@gmail.com

copyright:
  year:             2019
  name:             Tyler Thrailkill

# Google-analytics
# google-analytics:
  # id:               ""

# Disqus
# disqus:
  # id:               "kiko-plus"

# URL
url:                "http://tylerthrailkill.com" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           America/Denver
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "about"
    url:            "/about"
  - name:           "setup"
    url:            "/setup"
  - name:           "archive"
    url:            "/archive"
  - name:           "tags"
    url:            "/tags"
  - name:           "github"
    url:            "https://github.com/snowe2010/"
# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]